/**
 * Strategy library ported from the TradeCaptain backend foundation.
 * These are descriptive strategy labels used by proposals and bots —
 * they describe intent, never fabricated fills.
 */

import { query } from "./_generated/server";

export const STRATEGIES: Record<string, readonly string[]> = {
  STOCK: [
    "Momentum / Trend Following",
    "Swing Trading",
    "Breakout",
    "Mean Reversion",
    "Earnings / Catalyst",
    "Pairs / Statistical Arbitrage",
    "Value + Fundamental",
    "Sector Rotation",
    "Gap / Intraday",
    "Position / Long-Term Trend",
  ],
  CRYPTO: [
    "Trend Following",
    "Momentum",
    "Mean Reversion",
    "Breakout",
    "Grid",
    "Adaptive DCA",
    "Statistical Arbitrage",
    "Cross-Market Relative Value",
    "Funding / Basis",
    "Volatility / Regime",
  ],
  DERIVATIVES: [
    "Futures Trend Following",
    "Calendar / Intermarket Spread",
    "Vertical Option Spreads",
    "Long Straddle / Strangle",
    "Iron Condor",
    "Calendar / Time Spread",
    "Covered Call / Cash-Secured Put",
    "Protective Put / Collar",
    "Basis / Cash-and-Carry",
    "Delta-Neutral / Volatility",
  ],
  FOREX: [
    "Trend Following",
    "Carry",
    "Breakout",
    "Mean Reversion",
    "Momentum",
    "Volatility Breakout",
    "Pairs / Relative Value",
    "Macro Regime",
    "Session Momentum",
    "Multi-Timeframe Trend",
  ],
  BONDS: [
    "Yield Ladder",
    "Treasury Ladder",
    "Duration Rotation",
    "Credit Spread",
    "Investment-Grade Income",
    "High-Yield Allocation",
    "Rate-Cycle Positioning",
    "Bond ETF Momentum",
    "Inflation Protection",
    "Fixed-Income Diversification",
  ],
  COMMODITIES: [
    "Trend Following",
    "Seasonality",
    "Futures Curve",
    "Calendar Spread",
    "Intercommodity Spread",
    "Momentum",
    "Mean Reversion",
    "Macro Regime",
    "Inflation Hedge",
    "Volatility Breakout",
  ],
  DOMAINS: [
    "Expired Domain Value",
    "Keyword Demand",
    "Short-Domain",
    "Comparable Sales",
    "Traffic / SEO",
    "Brandability",
    "Auction Mispricing",
    "Geographic Domain",
    "Trend / Event Domain",
    "Portfolio Rotation",
  ],
  ARTWORK: [
    "Artist Momentum",
    "Historical Appreciation",
    "Auction Comparable Value",
    "Emerging Artist",
    "Blue-Chip Artist",
    "Relative Value",
    "Diversification",
    "Liquidity Filter",
    "Long-Term Appreciation",
    "Collection Rotation",
  ],
  NFT: [
    "Collection Momentum",
    "Floor Momentum",
    "Relative Rarity",
    "Volume Breakout",
    "Liquidity Rotation",
    "Whale Activity",
    "Cross-Marketplace Pricing",
    "Mean Reversion",
    "Event / Catalyst",
    "Long-Term Digital Collectible",
  ],
  REAL_ESTATE: [
    "Income Yield",
    "Cap Rate",
    "Geographic Growth",
    "Cash Flow Quality",
    "Appreciation Potential",
    "Occupancy Stability",
    "REIT Momentum",
    "REIT Value",
    "Diversification",
    "Distribution Growth",
  ],
  COLLECTIBLES: [
    "Comparable Sales",
    "Grade Arbitrage",
    "Player / Creator Momentum",
    "Population Scarcity",
    "Auction Mispricing",
    "Rookie / Vintage",
    "Seasonal Demand",
    "Liquidity Ranking",
    "Collector Value",
    "Cross-Marketplace Arbitrage",
  ],
  TICKETS: [
    "Demand Momentum",
    "Sellout Probability",
    "Historical Price Comparison",
    "Time-to-Event",
    "Venue Demand",
    "Performer / Team Demand",
    "Seat Location Value",
    "Primary vs Resale Spread",
    "Geographic Demand",
    "Inventory Scarcity",
  ],
};

export const listStrategies = query({
  args: {},
  handler: async () => STRATEGIES,
});